### ISSUE TITLE
Support Existing VPC

### ISSUE THREAD

**Issue by ltagliamonte-dd** [instaclustr/terraform-provider-instaclustr#13]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Today via the Instaclustr console it is possible to provision a cluster using an existing VPC-ID.
Couldn't not find it in the public API documentation.
Please add support to the terraform provider as well.

**Comment by peter-toms** [comment]
thanks @ltagliamonte-dd, currently evaluating what we can do on this front and will update back here shortly :)
