### ISSUE TITLE
Provide a way to retrieve cluster password & certificate

### ISSUE THREAD

**Issue by cameronattard** [instaclustr/terraform-provider-instaclustr#24]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

It would be useful to be able to retrieve a cluster's instaclustr user password and certificate in Terraform. It looks like these properties are exposed in the `https://api.instaclustr.com/provisioning/v1/<clusterId>` endpoint as `instaclustrUserPassword` and `clusterCertificateDownload` (although it would be better to be able to retrieve the actual certificate body, not just a download link).

### New or Affected Resource(s)

* instaclustr_cluster

### References

* https://www.instaclustr.com/support/api-integrations/api-reference/provisioning-api/

**Comment by peter-toms** [comment]
thanks @cameronattard for the suggestion, ill discuss further with the team

**Comment by cameronattard** [comment]
Thanks @peter-toms. Has this made it onto the roadmap at all?

**Comment by peter-toms** [comment]
Unfortunately don't have an eta on this one as yet.  However, I'm looking at a package of work that will include this change, will keep you updated.
