### ISSUE TITLE
Expose AWS-generated VPC Peering Connection ID in resource outputs

### ISSUE THREAD

**Issue by evanfuller** [instaclustr/terraform-provider-instaclustr#29]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

I am currently writing some terraform to create a VPC peering connection from the Instaclustr account to my AWS account. I have a stencil written like:
```
resource "instaclustr_vpc_peering" "requester" {
  cluster_id      = instaclustr_cluster.cluster.id
  peer_vpc_id     = var.accepter_vpc_id
  peer_account_id = var.aws_account_id
  peer_subnet     = var.accepter_cidr_range
}

resource "aws_vpc_peering_connection_accepter" "accepter" {
  vpc_peering_connection_id = instaclustr_vpc_peering.requester.id
  auto_accept               = true
}
```

Unfortunately, at apply time, this fails with an error like:

```
Error: error reading VPC Peering Connection (76f821e3-dc93-4a48-9157-9fed9eea0aa4): InvalidVpcPeeringConnectionId.Malformed: Invalid id: "9442577b-6347-4b9e-923e-9a9a61189f75" (expecting "pcx-...")
	status code: 400, request id: ef9352dc-ac76-4a15-8140-07e63e32cc0d
```

Looking a little bit at the [source code](https://github.com/instaclustr/terraform-provider-instaclustr/blob/master/instaclustr/resource_vpc_peering.go#L115), I see that the `vpc_peering_id` property is currently set to the same as the `id` property. Prior to looking at the source code, I expected that the `vpc_peering_id` property would be set to the AWS-generated property (i.e. the `"pcx-..."` ID that it's asking for in the error message). Is it possible to make this property available in an attribute?

https://github.com/instaclustr/terraform-provider-instaclustr/blob/master/instaclustr/resource_vpc_peering.go#L115

### New or Affected Resource(s)

* instaclustr_vpc_peering

**Comment by slater-ben** [comment]
Hi Evan

From a quick look, it appears the terraform provider is not returning aws_vpc_connection_id from our provisioning API which is what you need. I will get the team to look into this. If you have an urgent requirement, please advise support@instaclustr.com so we can keep you apprised on progress.

Cheers
Ben
