### ISSUE TITLE
Allow terraform import

### ISSUE THREAD

**Issue by renaudhager** [instaclustr/terraform-provider-instaclustr#32]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

It could be very useful to leverage the `import` feature offer by Terraform. 
The idea is that any instaclustr resources that has been manually created can imported in the Terraform state, using `terraform import` command.

**Comment by peter-toms** [comment]
thanks for the suggestion @renaudhager ill raise it with the team and get back to you

**Comment by ProfMoo** [comment]
This would be HUGE for our workflow. Currently, we have a cluster defined in Terraform, but the name given to the Terraform resource is incorrect. AFAIK, there isn't a way to change that without deleting the resource and recreating. `import` could help out here.

**Comment by slater-ben** [comment]
INS-8583 corresponding Instaclustr internal issue

**Comment by Chrismelba-Instaclustr** [comment]
This has been added with v1.8. Thanks everyone for the suggestion!
