### ISSUE TITLE
Ability to Add and Manage Users 

### ISSUE THREAD

**Issue by ProfMoo** [instaclustr/terraform-provider-instaclustr#35]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

It'd be very helpful if we could manage Instaclustr users through Terraform. The workflow could be very similar to how AWS allows managing IAM Users through Terraform.

### New or Affected Resource(s)

* instaclustr_user

### Potential Terraform Configuration

```hcl
resource "instaclustr_user" "my_user" {
  cluster_id = foo_cluster_id
  user       = foo_user
}
```

**Comment by peter-toms** [comment]
thanks for the suggestion @ProfMoo ill raise this with the team!

**Comment by peter-toms** [comment]
adding internal reference for this work: INS-8730

**Comment by peter-toms** [comment]
@ProfMoo a heads up that we have added the ability to add Kafka users in v1.3.0 of the provider https://github.com/instaclustr/terraform-provider-instaclustr/releases/tag/v1.3.0

**Comment by ProfMoo** [comment]
@peter-toms Thanks for following through on that!
