### ISSUE TITLE
Terraform v0.13 support

### ISSUE THREAD

**Issue by peter-toms** [instaclustr/terraform-provider-instaclustr#47]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Update the [Terraform provider in order to support v0.13](https://www.terraform.io/upgrade-guides/0-13.html)

### New or Affected Resource(s)

TBA

**Comment by peter-toms** [comment]
Adding internal reference INS-9184

**Comment by Chrismelba-Instaclustr** [comment]
We now support TF0.13
