### ISSUE TITLE
Wait for cluster to be running before creating user

### ISSUE THREAD

**Issue by ghost** [instaclustr/terraform-provider-instaclustr#49]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

 TF 0.13.2

### Affected Resource(s)

* instaclustr_cluster and instaclustr_kafka_user

### Terraform Configuration Files

```hcl
resource instaclustr_cluster kafka {
  count                   = var.enable_instaclustr_kafka ? 1 : 0
  cluster_name            = "kafka-${var.name}"
  node_size               = var.kafka_node_size
  data_centre             = lookup(var.kafka_region, var.cluster_region, "AP_SOUTHEAST_2")
  sla_tier                = "NON_PRODUCTION"
  cluster_network         = var.kafka_cidr
  private_network_cluster = true
  cluster_provider = {
    name = "AWS_VPC"
  }
  rack_allocation = {
    number_of_racks = 3
    nodes_per_rack  = 1
  }
  bundle {
    bundle  = "KAFKA"
    version = "2.4.1"
  }
}
resource instaclustr_kafka_user kafka {
  count               = var.enable_instaclustr_kafka ? 1 : 0
  depends_on          = [instaclustr_cluster.kafka]
  cluster_id          = instaclustr_cluster.kafka[0].cluster_id
  username            = var.kafka_user_name
  password            = trimspace(var.kafka_user_password)
  initial_permissions = "standard"
}
```

### Expected Behavior

The user resource waits for the cluster resource to be in state of running and retry the user creation successfully.

### Actual Behavior

The user resource tries to create the user inside kafka and fails because the cluster is still starting.
After cluster running another manually `apply` creates the user.

### Steps to Reproduce

Create  kafka cluster and a user in that cluster just as I have it in attached configuration.

### References

* #0000

**Comment by peter-toms** [comment]
Thanks very much for the details @janlud I will raise this with the team

**Comment by peter-toms** [comment]
adding internal reference for this work: INS-10935
