### ISSUE TITLE
Provide compiled releases

### ISSUE THREAD

**Issue by benbromhead** [instaclustr/terraform-provider-instaclustr#5]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Provide a compiled release of the terraform provider (for osx, linux and windows). Release via github.com.

This way people can easily use the terraform provider without having to setup a go development chain. Which can be time consuming for those new to the go ecosystem.

### New or Affected Resource(s)

None. Compile, upload and release

**Comment by arihantsurana** [comment]
It would also be great if the provider was published to the official terraform provider registery.

**Comment by peter-toms** [comment]
> It would also be great if the provider was published to the official terraform provider registery.

Thanks @arihantsurana enhancement added to track that: https://github.com/instaclustr/terraform-provider-instaclustr/issues/7

**Comment by peter-toms** [comment]
great suggestion thanks @benbromhead am investigating the best option on this and will get it setup!
