### ISSUE TITLE
Support provider authentication initialization via environment variables

### ISSUE THREAD

**Issue by comjf** [instaclustr/terraform-provider-instaclustr#54]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Support provider configuration via ENV variables. Currently you expose `IC_API_KEY` and `IC_USERNAME` ENV variables for use with acceptance tests, but it does not work for a general use.

We use terragrunt on top of terraform, so the existing functionality of prompting at execute time does *not* work for our use-case. Please support multiple ways of providing the authentication details... I suggest using the existing ENV variables, as [ the github provider does this](https://github.com/terraform-providers/terraform-provider-github/blob/master/github/provider.go#L14), but really any solution that doesn't require me to hardcode secrets into our terraform configuration will work.

### New or Affected Resource(s)

* provider "instaclustr"  // initial authentication

**Comment by peter-toms** [comment]
thanks for the suggestion @comjf I will raise with the team 👍

**Comment by peter-toms** [comment]
adding internal reference for this work: INS-11385

**Comment by Chrismelba-Instaclustr** [comment]
Hi @comjf I think that the following should work:

To use environment variables with the instaclustr terraform client follow these steps:

In console export the desired variable:
`Export api_key={instaclustrAPIkey}`
In your main.tf file create a variable:
```
variable "api_key" {
 type = string
 default = "xxx"
}
```
In the provider block use the variable:
```
Provider "instaclustr" {
    username={username}
    api_key = var.api_key
}
```
When running terraform plan/apply, pipe in the variables as follows:
`Terraform apply -var= "api_key=$api_key"`

I've created a PR to update the readme.md and will close this issue.
