### ISSUE TITLE
1.9.6 doesn't work on MacOS 10.15

### ISSUE THREAD

**Issue by v-yarotsky** [instaclustr/terraform-provider-instaclustr#93]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

`0.13.1`

### Debug Output

```
Failed to instantiate provider "registry.terraform.io/instaclustr/instaclustr"
to obtain schema: fork/exec
.terraform/plugins/registry.terraform.io/instaclustr/instaclustr/1.9.6/darwin_amd64/terraform-p
exec format error
```

### Important Factoids

* Executing 1.9.6 binary directly results in:

      › ./terraform-provider-instaclustr_v1.9.6
      -bash: ./terraform-provider-instaclustr_v1.9.6: cannot execute binary file

* MacOS version:

      › sw_vers
      ProductName:    Mac OS X
      ProductVersion: 10.15.7
      BuildVersion:   19H524
      
* Version 1.9.5 works just fine.

**Comment by Chrismelba-Instaclustr** [comment]
Thanks for bringing this to our attention. Can confirm I can replicate the bug on my local machine. If you need functionality in 1.9.6 then building and installing locally seems to still work, otherwise your solution of using 1.9.5 is also fine.

**Comment by Chrismelba-Instaclustr** [comment]
Looks to be to do with dodgey binary names. Please check version 1.9.7 as hopefully that will have fixed the problem.

**Comment by peter-toms** [comment]
Just a note to follow up on this one, it does appear to have been a bad release (1.9.6) and we have subsequently removed it.  Thanks.
